apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  selector:
      matchLabels:
        run: redis
  replicas: 1
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - name: redis-1
        image: redis
        imagePullPolicy: Always
        ports:
          - name: port-6379
            containerPort: 6379
            protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
