apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    name: port-80
    targetPort: 6379
  selector:
    run: redis
  type: ClusterIP
