apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: port-6379
    targetPort: 6379
  selector:
    run: redis
  type: ClusterIP
